variables:
  PG_VERSION: "14"
  RUST_VERSION: "1.58"
  NODE_VERSION: "16"
  POSTGRES_DB: hook0-ci
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: trust

stages:
  - build
  - test
  - release

rust.check:
  stage: test
  image: rust:$RUST_VERSION
  only:
    changes:
      - api/**/*
      - output-worker/**/*
      - sentry-integration/**/*
      - Cargo.*
  variables:
    SQLX_OFFLINE: "true"
  services:
    - postgres:$PG_VERSION
  before_script:
    - rustc --version && cargo --version
    - rustup component add clippy
    - rustup component add rustfmt
  script:
    # Global
    - cargo fmt --all -- --check
    # Sentry integration
    - pushd sentry-integration
    - cargo clippy --all-targets --all-features -- -D warnings
    - cargo test
    - popd
    # API
    - pushd api
    - cargo clippy --all-targets --all-features -- -D warnings
    - cargo test
    - popd
    # Output Worker
    - pushd output-worker
    - cargo clippy --all-targets --all-features -- -D warnings
    - cargo test
    - popd

include:
  - local: 'frontend/.gitlab-ci.yml'
  - local: 'website/.gitlab-ci.yml'
  - local: 'api/.gitlab-ci.yml'
