website.build:
  stage: build
  dependencies: []
  rules:
    - changes:
        - website/**/*
  image: node:$NODE_VERSION
  script:
    - pushd website/
    - npm ci
    - npm run build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: push
    paths:
      - .npm
      - website/node_modules/
      - website/.parcel-cache/
  artifacts:
    paths:
      - website/dist

.website-release-tmpl: &website-release-tmpl
  stage: release
  image: node:$NODE_VERSION
  needs:
    - job: website.build
      artifacts: true
  before_script:
    - pushd website/
    # https://github.com/netlify/cli/issues/1870
    - npm i -g --unsafe-perm netlify-cli
  script:
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod --dir=dist/
  environment:
    name: production-website
    url: https://www.hook0.com
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      changes:
        - website/**/*

website.release:
  <<: *website-release-tmpl

website.release.manual:
  <<: *website-release-tmpl
  when: manual
